#version 430

layout(std140, binding = 0) buffer VectorA {int vecA[];};
layout(std140, binding = 1) buffer VectorB {int vecB[];};
layout(std140, binding = 2) buffer VectorC {int vecC[];};

uniform int numberOfElements;

layout(local_size_x = 512, local_size_y = 1, local_size_z = 1) in;
void main() {
	uint index = gl_GlobalInvocationID.x;
	if(index < numberOfElements)
		vecC[index]=vecA[index]+vecB[index];
};